name: Build and Test Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
